#!/bin/sh

# matar instancias multiplicables del inicio anterior
killall lemonbar stalonetray &

# inicio

sxhkd &
compton --config ~/.config/compton/compton.conf &
wmname LG3D &
nitrogen --restore &

# Escritorios
bspc monitor -d 一 二 三 四 五 六 七 八 九 零
#bspc monitor -d α β γ δ ε ς ζ η θ ι
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d I II III IV V VI VII VIII IX X

# Configuracion de BSPWM
# mod1 = tecla windows
bspc config pointer_modifier mod1
# Reglas de ventanas
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# colores
bspc config presel_feedback_color \#FF007F
bspc config focused_border_color \#FF007F
#bspc config normal_border_color \#


# reglas para ventanas especificas
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a "install4j-chemaxon-marvin-SketchApplication" state=floating
bspc rule -a Imagen sobre imagen state=floating

# Barras
dash ~/.config/lemonbar/engineerbar | lemonbar -p -f "Hack:lang=zh-cn:style=regular:pixelsize=12" -n "bar" -b &

#lemonbar -b -p -f "Hack:style=Regular:lang=ja:pixelsize=12"  &
# -f "Hack Nerd Font:style=Regular"

# Teclado
ibus-daemon -drx &

#export GTK_IM_MODULE=ibus
#export QT4_IM_MODULE=xim
#export QT_IM_MODULE=xim
#export XMODIFIERS=@im=ibus

# Renombramientos
# Nuevos escritorios
xsetroot -name "Nuevo escritorio" &

# Bandeja de sistema (system tray)
(sleep 3 && stalonetray) &

# trayer --edge bottom --align right --width 4 --height 20 --SetDockType true --SetPartialStrut true --expand true --transparent true --distancefrom right --distance 295  &
#

# Renombrar barra
# xprop -name "stalonetray" -f WM_TRUC 8s -set WM_TRUC "The_Truc"
#xprop -name "stalonetray" -f WM_CLASS 8s -set WM_CLASS "stalonetray" &
#xprop -name "stalonetray" -f WM_NAME 8s -set WM_NAME "stalonetray" &

# Cloud

insync start & 

