#!/usr/bin/bash

Clock(){
	TIME=$(date "+%A %d,  %B %Y. · %T")
	echo "${TIME}" 
}

ActiveWindow(){
	len=$(echo -n "$(xdotool getwindowfocus getwindowname)" | wc -m)
	max_len=70
	if [ "$len" -gt "$max_len" ];then
		echo -n "$(xdotool getwindowfocus getwindowname | cut -c 1-$max_len)..."
	else
		echo -n "$(xdotool getwindowfocus getwindowname)"
	fi
}

ActiveDesktop(){
		ACTIVEDESKTOP=$(bspc query -D -d --names)
		echo -n "$ACTIVEDESKTOP"
}

OccupiedDesktops(){
	actual=$(bspc query -D -d --names)
	coloreado=$(awk 'BEGIN{"bspc query -D -d --names"|getline usando;print "%{B#BE005577}%{+u}"usando"%{B#22000000}%{-u}"}')
	reemplazar=$(bspc query -D -d .occupied --names | sed "s/$actual/$coloreado/")
	
	OD=$(echo "$reemplazar"| paste -d' ' -s)
	
	echo -n "$OD"
}


Battery() {
	BATTACPI=$(acpi --battery)
	BATPERC=$(echo $BATTACPI | cut -d, -f2 | tr -d '[:space:]')

	if [[ $BATTACPI == *"100%"* ]]
	then
		echo -e -n "\uf00c $BATPERC"
	elif [[ $BATTACPI == *"Discharging"* ]]
	then
		BATPERC=${BATPERC::-1}
		if [ $BATPERC -le "10" ]
		then
			echo -e -n "\uf244"
		elif [ $BATPERC -le "25" ]
		then
			echo -e -n "\uf243"
		elif [ $BATPERC -le "50" ]
		then
			echo -e -n "\uf242"
		elif [ $BATPERC -le "75" ]
		then
			echo -e -n "\uf241"
		elif [ $BATPERC -le "100" ]
		then
			echo -e -n "\uf240"
		fi
		echo -e " $BATPERC%"
	elif [[ $BATTACPI == *"Charging"* && $BATTACPI != *"100%"* ]]
	then
		echo -e "\uf0e7 $BATPERC"
	elif [[ $BATTACPI == *"Unknown"* ]]
	then
		echo -e "$BATPERC"
	fi
}


Language(){
	CURRENTLANG=$(locale | awk -F= 'NR==1{print $2}')
	echo -n "$CURRENTLANG"
}

while true; do
	echo -e "%{l}$(OccupiedDesktops) ·" "%{c}$(ActiveDesktop) · $(ActiveWindow)" "%{r}$(Language) · $(Clock)"
	sleep 0.1s
done
